import type { GameId, GameMeta } from "./types";

export const GAMES: GameMeta[] = [
  {
    id: "balloon",
    name: "Balloon",
    kicker: "Risk calibration",
    skill: "Decision-making under uncertainty",
    description: "Bank gains before a hidden pressure threshold bursts the balloon.",
    accent: "#3578f6",
    glyph: "BL",
    controls: "Space to pump · Enter to cash out · buttons also work",
    scoring: "Banked value and explosion rate drive the Practice Score; adjusted pumps and risk consistency remain visible raw metrics.",
    example: "Pump to raise a balloon from $0 to $1, then bank it before it bursts.",
    failure: "Pumping at the hidden breakpoint bursts the balloon and loses its temporary value.",
  },
  {
    id: "skyscraper",
    name: "Skyscraper",
    kicker: "Planning",
    skill: "Multi-step planning and inhibition",
    description: "Move a tower between pads using one legal move at a time.",
    accent: "#7d6af1",
    glyph: "SK",
    controls: "Click a source tower, then a destination tower.",
    scoring: "Planning efficiency compares your move count with the optimal solution.",
    example: "A smaller floor may sit on a larger floor, never the reverse.",
    failure: "Illegal moves are rejected and reduce efficiency.",
  },
  {
    id: "shapeshift",
    name: "Shapeshift",
    kicker: "Response control",
    skill: "Rule mapping and reaction speed",
    description: "Translate each shape into its mapped direction under time pressure.",
    accent: "#ec5d85",
    glyph: "SH",
    controls: "Arrow keys or the on-screen direction pad.",
    scoring: "Accuracy, median reaction time, consistency, and anticipations.",
    example: "If triangle maps to left, press ← when a triangle appears.",
    failure: "A wrong direction or response timeout counts as an error.",
  },
  {
    id: "code-compare",
    name: "Code Compare",
    kicker: "Visual precision",
    skill: "Rapid visual discrimination",
    description: "Find the single code that exactly matches the reference.",
    accent: "#00a78e",
    glyph: "CC",
    controls: "Keys 1–4 or click a candidate.",
    scoring: "Accuracy and reaction time by code length and mismatch position.",
    example: "Reference A7K2 matches only the candidate with every character intact.",
    failure: "Choosing a one-character distractor or timing out counts as an error.",
  },
  {
    id: "pincode",
    name: "Pincode",
    kicker: "Working memory",
    skill: "Digit span and transformation",
    description: "Hold a digit sequence, transform it, then enter the result.",
    accent: "#e7a323",
    glyph: "PI",
    controls: "Number keys, Backspace, and Enter or keypad buttons.",
    scoring: "Recall accuracy, maximum span, transformation accuracy, and recall time.",
    example: "Reverse 3 8 1 into 1 8 3 after the sequence disappears.",
    failure: "An incorrect transformed sequence ends that round.",
  },
  {
    id: "number-box",
    name: "Number Box",
    kicker: "Numerical reasoning",
    skill: "Arithmetic search and constraint control",
    description: "Use every supplied number exactly once to reach the target.",
    accent: "#e06b35",
    glyph: "NB",
    controls: "Type an expression or use the keypad, then submit.",
    scoring: "Solve rate, valid expression rate, and solve time.",
    example: "For 2, 3, 4 → 20, enter (2+3)×4.",
    failure: "Invalid math or failing to use each number exactly once is rejected.",
  },
  {
    id: "figure-it-out",
    name: "Figure It Out",
    kicker: "Hypothesis testing",
    skill: "Information-efficient reasoning",
    description: "Deduce a hidden figure using structured feedback after each guess.",
    accent: "#2aa4c4",
    glyph: "FI",
    controls: "Choose color, shape, and count, then submit a guess.",
    scoring: "Guesses, information gain, repeated guesses, and solve efficiency.",
    example: "A clue tells you how many attributes match exactly and how many differ.",
    failure: "The puzzle ends after the guess limit if the exact figure is not found.",
  },
  {
    id: "switch",
    name: "The Switch",
    kicker: "Cognitive flexibility",
    skill: "Task switching and selective attention",
    description: "Answer only the cued task while two competing tasks remain visible.",
    accent: "#9864d8",
    glyph: "SW",
    controls: "F = No · J = Yes · buttons also work",
    scoring: "Switch cost, repeat RT, switch accuracy, and timeouts.",
    example: "When NUMBER is cued, ignore the arrows and judge the arithmetic result.",
    failure: "Answering the uncued task or missing the response window is incorrect.",
  },
  {
    id: "stock-master",
    name: "Stock Master",
    kicker: "Divided attention",
    skill: "Prediction, timing, and precision",
    description: "Activate rotating gauges while their needles cross a target zone.",
    accent: "#1380bb",
    glyph: "SM",
    controls: "Keys 1–9 or click a gauge.",
    scoring: "Hits, angular precision, early/late balance, and timing error.",
    example: "Press 2 when gauge 2’s needle is centered inside its marked arc.",
    failure: "Early, late, or missed activations reduce precision.",
  },
];

export const GAME_MAP = Object.fromEntries(
  GAMES.map((game) => [game.id, game]),
) as Record<GameId, GameMeta>;

export const GAME_ORDER = GAMES.map((game) => game.id);
