import type { GameId, GameMeta } from "./types";

export const GAMES: GameMeta[] = [
  {
    id: "balloon",
    name: "Balloon",
    kicker: "Risk calibration",
    skill: "Decision-making under uncertainty",
    description: "Pump balloons for temporary earnings, then bank them before an unknown burst point.",
    accent: "#3578f6",
    glyph: "BL",
    controls: "Space to pump · Enter to collect · buttons also work",
    scoring: "Adjusted average pumps, permanent earnings, explosions, and post-burst adaptation describe your risk strategy.",
    example: "Each pump grows the balloon and its temporary value; Collect moves that value into your permanent bank.",
    failure: "A burst loses only the current balloon's temporary value and immediately starts the next trial.",
  },
  {
    id: "skyscraper",
    name: "Skyscraper",
    kicker: "Planning",
    skill: "Multi-step planning and inhibition",
    description: "Move top blocks between stacks until the live towers exactly match a target structure.",
    accent: "#7d6af1",
    glyph: "SK",
    controls: "Click a source tower, then a destination tower.",
    scoring: "Planning efficiency compares your move count with the optimal solution.",
    example: "Select the stack holding a blue top block, then select the stack where the target places it.",
    failure: "Only exposed top blocks can move; empty-source and unnecessary moves reduce efficiency.",
  },
  {
    id: "shapeshift",
    name: "Shapeshift",
    kicker: "Response control",
    skill: "Selective attention and inhibitory control",
    description: "Classify circles and squares while ignoring whether they flash on the left or right.",
    accent: "#ec5d85",
    glyph: "SH",
    controls: "Left/Right arrow keys or the two on-screen response buttons.",
    scoring: "Accuracy, reaction time, and the interference cost between congruent and incongruent trials.",
    example: "If circle means left, press ← for a circle even when it appears on the right side.",
    failure: "Responding to screen position instead of shape identity, or timing out, counts as an error.",
  },
  {
    id: "code-compare",
    name: "Code Compare",
    kicker: "Visual precision",
    skill: "Rapid visual discrimination",
    description: "Match a numeric reference code to the one identical option before its short window closes.",
    accent: "#00a78e",
    glyph: "CC",
    controls: "Keys 1–4 or click a candidate.",
    scoring: "Accuracy and reaction time by code length and mismatch position.",
    example: "Reference 731804 matches only the candidate with every digit in the same position.",
    failure: "Choosing a one-digit distractor or missing the response window loses that opportunity.",
  },
  {
    id: "pincode",
    name: "Digit",
    kicker: "Working memory",
    skill: "Sequential digit span and manipulation",
    description: "Watch digits flash one at a time, then repeat, reverse, or sort each sequence by phase.",
    accent: "#e7a323",
    glyph: "PI",
    controls: "Number keys, Backspace, and Enter or keypad buttons.",
    scoring: "Score per minute, accuracy, maximum span, and separate Repeat/Reverse/Sort performance.",
    example: "In the Reverse block, digits 3, 8, 1 must be entered as 1, 8, 3 after they disappear.",
    failure: "An incorrect transformed sequence ends that round.",
  },
  {
    id: "number-box",
    name: "Number Box",
    kicker: "Numerical reasoning",
    skill: "Arithmetic search and constraint control",
    description: "Combine four numbers exactly once with arithmetic operations to make 24.",
    accent: "#e06b35",
    glyph: "NB",
    controls: "Click number → operator → number; use Undo, Reset, or Skip as needed.",
    scoring: "Solve speed, skip cost, valid operations, and puzzle rarity contribute to the result.",
    example: "For 2, 3, 4, 4: combine 4−2, then 2×3, then 6×4 to make 24.",
    failure: "A number cannot be reused; invalid division is rejected and skipping carries a penalty.",
  },
  {
    id: "figure-it-out",
    name: "Figure It Out",
    kicker: "Hypothesis testing",
    skill: "Information-efficient reasoning",
    description: "Deduce one hidden figure's color, shape, and pattern from aggregate attribute feedback.",
    accent: "#2aa4c4",
    glyph: "FI",
    controls: "Choose color, shape, and pattern, then submit a complete guess.",
    scoring: "Guesses, information gain, repeated guesses, and solve efficiency.",
    example: "A clue tells you how many attributes match exactly and how many differ.",
    failure: "The puzzle ends after the guess limit if the exact figure is not found.",
  },
  {
    id: "switch",
    name: "The Switch",
    kicker: "Cognitive flexibility",
    skill: "Task switching and selective attention",
    description: "Use a prompt's screen position to decide whether to judge arithmetic or compare arrows.",
    accent: "#9864d8",
    glyph: "SW",
    controls: "F = No · J = Yes · buttons also work",
    scoring: "Switch cost, repeat RT, switch accuracy, and timeouts.",
    example: "A prompt above the divider uses the Number rule; below the divider it uses the Arrow rule.",
    failure: "Applying the previous position's rule or missing the response window is incorrect.",
  },
  {
    id: "stock-master",
    name: "Stock Master",
    kicker: "Divided attention",
    skill: "Prediction, timing, and precision",
    description: "Track rising speedometers and activate each one inside its optimal target zone.",
    accent: "#1380bb",
    glyph: "SM",
    controls: "Keys 1–9 or click a gauge.",
    scoring: "Hits, streak, precision, early/late balance, misses, and timing error.",
    example: "Press 2 when gauge 2’s needle is centered inside its marked arc.",
    failure: "Early, late, or missed activations reduce precision.",
  },
];

export const GAME_MAP = Object.fromEntries(
  GAMES.map((game) => [game.id, game]),
) as Record<GameId, GameMeta>;

export const GAME_ORDER = GAMES.map((game) => game.id);
